#!/bin/bash

backup::get_filename() {
  local name=$1
  if [ -z "$name" ]; then
    log::error "[backup::get_filename] name is required"
    return 1
  fi

  local timestamp=$(date +%Y_%m_%d_%H_%M)
  echo "${PLUGIN_BACKUP_DIR}/backup_${name}_${timestamp}.tar.xz"
}

export -f backup::get_filename
