#!/bin/bash

backup::create() {
  local name=$1
  local dirs=${@:2}

  if [ -z "$name" ]; then
    log::error "[backup::create] name is required"
    return 1
  fi

  if [ -z "$dirs" ]; then
    log::error "[backup::create] dirs is required"
    return 1
  fi

  local backup_filepath=$(backup::get_filename $name)

  for dir in $dirs; do
    if [ ! -d "$dir" ]; then
      log::error "[backup::create] backup dir ($dir) not found"
      return 1
    fi

    if [ -z "$(ls $dir)" ]; then
      log::error "[backup::create] backup dir ($dir) is empty"
      return 1
    fi
  done

  log::info "backup $backup_filepath with dirs: $dirs ..."
  # sudo tar -zcvf $backup_filepath $dirs
  # donot need force sudo
  tar -zcvf $backup_filepath $dirs
  if [ "$?" != "0" ]; then
    log::error "[backup::create] failed to create backup file: $backup_filepath"
    return 1
  else
    log::success "[backup::create] successfully created backup file: $backup_filepath"
    return 0
  fi
}

export -f backup::create
